<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INIDC-sawantsh2" name="Test Two" tests="2" failures="1" timestamp="10 Jul 2019 10:46:45 GMT" time="29.634" errors="0">
  <testcase name="loginTest" time="3.507" classname="com.qa.test.WebShopLoginTest"/>
  <testcase name="loginTest" time="11.865" classname="com.qa.test.WebShopLoginTest">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;...rrors and try again.[]
The credentials pro...&amp;gt; but was:&amp;lt;...rrors and try again.[]
The credentials pro...&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...rrors and try again.[
]
The credentials pro...> but was:<...rrors and try again.[]
The credentials pro...>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at com.qa.pages.WebShopLogin.logoutWebshop(WebShopLogin.java:54)
	at com.qa.test.WebShopLoginTest.loginTest(WebShopLoginTest.java:41)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test Two -->
